version: "3.9"

services:
  app:
    build:
      context: .
    image: dvasilevich/skypro_hw_26
    ports:
      - 8000:8000
    volumes:
      - ./app_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    volumes:
      - ./app_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: hw_26
      POSTGRES_PASSWORD: hw_26_password
      POSTGRES_DB: hw_26
    volumes:
      - ./hw26_data:/var/lib/postgresql/data 700
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hw_26" ]
      interval: 5s
      timeout: 5s
      retries: 5
