version: "3.9"

services:
  app:
    build:
      context: .
    image: dvasilevich/skypro_hw_26
    ports:
      - "80:80"
    volumes:
      - ./app_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
  migrations:
    build:
      context: .
    volumes:
      - ./app_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./hw26_data:/var/lib/postgresql/data 700
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
